In [2]:
import numpy as np 
import cv2 

In [3]:
img = cv2.imread('../../data/avengers.jpg',0)

In [4]:
img.shape, img.ndim

((1441, 2560), 2)

In [1]:
import numpy as np

def dilation(image, selem):
    """Perform dilation on a 2-D image using a given structuring element.
    
    # Define the shape of the structuring element
    selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)
    """
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.max(sub_image + selem)
    return result

# Load the input image
image = np.array([[0, 0, 1, 1, 0, 0],
                  [0, 1, 1, 1, 1, 0],
                  [1, 1, 1, 1, 1, 1],
                  [0, 0, 1, 1, 0, 0],
                  [0, 0, 1, 1, 0, 0]], dtype=np.uint8)

# Define the shape of the structuring element
selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)

# Apply the dilation operation
result = dilation(image, selem)

print("Input Image:\n", image)
print("Dilated Result:\n", result)


Input Image:
 [[0 0 1 1 0 0]
 [0 1 1 1 1 0]
 [1 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
Dilated Result:
 [[2 2 2 2 0 0]
 [2 2 2 2 0 0]
 [2 2 2 2 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [6]:
dil = dilation(img, selem)

In [7]:
cv2.imshow('wn',dil)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import numpy as np

def erosion(image, selem):
    """Perform erosion on a 2-D image using a given structuring element.
    # Define the shape of the structuring element
    selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)

    
    
    """
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.min(sub_image * selem)
    return result

# Load the input image
image = np.array([[0, 0, 1, 1, 0, 0],
                  [0, 1, 1, 1, 1, 0],
                  [1, 1, 1, 1, 1, 1],
                  [0, 0, 1, 1, 0, 0],
                  [0, 0, 1, 1, 0, 0]], dtype=np.uint8)

# Define the shape of the structuring element
selem = np.array([[2, 2, 1],
                  [3, 4, 1],
                  [4, 3, 6]], dtype=np.uint8)

# Apply the erosion operation
result = erosion(image, selem)

print("Input Image:\n", image)
print("Eroded Result:\n", result)


Input Image:
 [[0 0 1 1 0 0]
 [0 1 1 1 1 0]
 [1 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
Eroded Result:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [18]:
erode=erosion(img,selem)

In [20]:
cv2.imshow('wn',erode)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
erode

array([[44, 63, 50, ..., 47,  0,  0],
       [21, 17, 27, ..., 46,  0,  0],
       [17, 14, 22, ..., 44,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [21]:
import numpy as np

def black_hat(image, selem):
    """Perform black-hat transform on a 2-D image using a given structuring element."""
    erosion_result = erosion(image, selem)
    dilation_result = dilation(erosion_result, selem)
    result = image - dilation_result
    return result

def erosion(image, selem):
    """Perform erosion on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.min(sub_image * selem)
    return result

def dilation(image, selem):
    """Perform dilation on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.max(sub_image + selem)
    return result

# Load the input image
image = np.array([[0, 0, 1, 1, 0, 0],
                  [0, 1, 1, 1, 1, 0],
                  [1, 1, 1, 1, 1, 1],
                  [0, 0, 1, 1, 0, 0],
                  [0, 0, 1, 1, 0, 0]], dtype=np.uint8)

# Define the shape of the structuring element
selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)

# Apply the black-hat transform
result = black_hat(image, selem)

print("Input Image:\n", image)
print("Black-hat Result:\n", result)


Input Image:
 [[0 0 1 1 0 0]
 [0 1 1 1 1 0]
 [1 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
Black-hat Result:
 [[255 255   0   0   0   0]
 [255   0   0   0   1   0]
 [  0   0   0   0   1   1]
 [  0   0   1   1   0   0]
 [  0   0   1   1   0   0]]


In [22]:
import numpy as np

def black_hat(image, selem):
    """Perform black-hat transform on a 2-D image using a given structuring element."""
    erosion_result = erosion(image, selem)
    dilation_result = dilation(erosion_result, selem)
    result = image - dilation_result
    return result

def erosion(image, selem):
    """Perform erosion on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.min(sub_image * selem)
    return result

def dilation(image, selem):
    """Perform dilation on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.max(sub_image + selem)
    return result

# Load the input image
image = np.array([[0, 0, 1, 1, 0, 0],
                  [0, 1, 1, 1, 1, 0],
                  [1, 1, 1, 1, 1, 1],
                  [0, 0, 1, 1, 0, 0],
                  [0, 0, 1, 1, 0, 0]], dtype=np.uint8)

# Define the shape of the structuring element
selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)

# Apply the black-hat transform
result = black_hat(image, selem)

print("Input Image:\n", image)
print("Black-hat Result:\n", result)


Input Image:
 [[0 0 1 1 0 0]
 [0 1 1 1 1 0]
 [1 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]]
Black-hat Result:
 [[255 255   0   0   0   0]
 [255   0   0   0   1   0]
 [  0   0   0   0   1   1]
 [  0   0   1   1   0   0]
 [  0   0   1   1   0   0]]


In [ ]:
import numpy as np

def top_hat(image, selem):
    """Perform top-hat transform on a 2-D image using a given structuring element."""
    dilation_result = dilation(image, selem)
    erosion_result = erosion(dilation_result, selem)
    result = dilation_result - erosion_result
    return result

def erosion(image, selem):
    """Perform erosion on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.min(sub_image * selem)
    return result

def dilation(image, selem):
    """Perform dilation on a 2-D image using a given structuring element."""
    result = np.zeros_like(image)
    for i in range(image.shape[0] - selem.shape[0] + 1):
        for j in range(image.shape[1] - selem.shape[1] + 1):
            sub_image = image[i:i+selem.shape[0], j:j+selem.shape[1]]
            result[i, j] = np.max(sub_image + selem)
    return result

# Load the input image
image = np.array([[0, 0, 1, 1, 0, 0],
                  [0, 1, 1, 1, 1, 0],
                  [1, 1, 1, 1, 1, 1],
                  [0, 0, 1, 1, 0, 0],
                  [0, 0, 1, 1, 0, 0]], dtype=np.uint8)

# Define the shape of the structuring element
selem = np.array([[0, 1, 0],
                  [1, 1, 1],
                  [0, 1, 0]], dtype=np.uint8)

# Apply the top-hat transform
result = top_hat(image, selem)

print("Input Image:\n", image)
print("Top-hat Result:\n", result)
